//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbEmptransaction
    {
        public int TransactionNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<int> Line { get; set; }
        public Nullable<int> Section { get; set; }
        public string WorkingStatus { get; set; }
        public string ClockIn { get; set; }
        public string ClockOut { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    }
}
