//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Reason
    {
        public int ReasonID { get; set; }
        public string ReasonName { get; set; }
        public string PlantName { get; set; }
        public string LineName { get; set; }
        public string ProductName { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SectionID { get; set; }
    }
}
