//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ServicesClocktime
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public string PlantName { get; set; }
        public string LineName { get; set; }
        public string SectionName { get; set; }
        public string ShiftName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string ClockIn { get; set; }
        public string ClockOut { get; set; }
        public string WorkingStatus { get; set; }
        public Nullable<int> QRCodePerUnit { get; set; }
        public Nullable<int> QRCodePerEmployee { get; set; }
        public Nullable<int> TransactionNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
