//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_EmployeeJoin
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public string QRCode { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<int> Line { get; set; }
        public Nullable<int> WorkingStatus { get; set; }
        public string ClockIn { get; set; }
        public string ClockOut { get; set; }
    }
}
